Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Areas/Admin/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoCapas.AccesoDatos.Data.Repository.IRepository;
using ProyectoCapas.Models;
using ProyectoCapas.Models.ViewModel;

namespace ProyectoCapas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ArticlesController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            ArticleCategoryViewModel articleCategoryViewModel = new ArticleCategoryViewModel()
            {
                Article = new Article(),
                ListCategories = _unitOfWork.ICategoryRepository.GetListCategories(),
            };

            return View(articleCategoryViewModel);
        }

        [HttpPost]
        public IActionResult Create(ArticleCategoryViewModel articleCategoryViewModel)
        {
            string mainRoute = _webHostEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            if (articleCategoryViewModel.Article.Id == 0 && files.Count() > 0)
            {
                string nameFile = Guid.NewGuid().ToString();
                string upload = Path.Combine(mainRoute, @"images\articles");
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStreams = new FileStream(Path.Combine(upload, nameFile + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStreams);
                }

                articleCategoryViewModel.Article.UrlImage = @"\images\articles\" + nameFile + extension;
                articleCategoryViewModel.Article.CreatedDate = DateTime.Now.ToString();

                _unitOfWork.IArticleRepository.Add(articleCategoryViewModel.Article);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            articleCategoryViewModel.ListCategories = _unitOfWork.ICategoryRepository.GetListCategories();
            return View(articleCategoryViewModel);
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ArticleCategoryViewModel articleCategoryViewModel = new ArticleCategoryViewModel()
            {
                Article = new Article(),
                ListCategories = _unitOfWork.ICategoryRepository.GetListCategories(),
            };
            if (id <= 0)
            {
                return BadRequest();
            }
            else
            {
                articleCategoryViewModel.Article = _unitOfWork.IArticleRepository.GetById(id);

                return View(articleCategoryViewModel);
            }
        }

        [HttpPost]
        public IActionResult Edit(ArticleCategoryViewModel articleCategoryViewModel)
        {
            string mainRoute = _webHostEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var articleFromDb = _unitOfWork.IArticleRepository.GetById(articleCategoryViewModel.Article.Id);

            if (files.Count() > 0)
            {
                string nameFile = Guid.NewGuid().ToString();
                string upload = Path.Combine(mainRoute, @"images\articles");
                var extension = Path.GetExtension(files[0].FileName);

                //Comprobar si existe la imagen
                var pathOldImage = Path.Combine(mainRoute, articleFromDb.UrlImage.TrimStart('\\'));
                if (System.IO.File.Exists(pathOldImage))
                {
                    System.IO.File.Delete(pathOldImage);
                }

                //Nuevamente subimos la imagen
                using (var fileStreams = new FileStream(Path.Combine(upload, nameFile + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStreams);
                }

                articleCategoryViewModel.Article.UrlImage = @"\images\articles\" + nameFile + extension;
                articleCategoryViewModel.Article.CreatedDate = DateTime.Now.ToString();

                _unitOfWork.IArticleRepository.Update(articleCategoryViewModel.Article);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                articleCategoryViewModel.Article.UrlImage = articleFromDb.UrlImage;
            }

            _unitOfWork.IArticleRepository.Update(articleCategoryViewModel.Article);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
        #endregion

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var articleFromDb = _unitOfWork.IArticleRepository.GetById(id);

            string mainRoute = _webHostEnvironment.WebRootPath;
            var pathOldImage = Path.Combine(mainRoute, articleFromDb.UrlImage.TrimStart('\\'));

            if (System.IO.File.Exists(pathOldImage))
            {
                System.IO.File.Delete(pathOldImage);
            }


            if (articleFromDb == null)
            {
                return Json(new { success = false, message = "El articulo no existe" });
            }
            _unitOfWork.IArticleRepository.Delete(id);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Articulo eliminado exitosamente" });
        }

        #region Call Apis

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new
            {
                data = _unitOfWork.IArticleRepository.GetAll(filter: x => x.IsActive,
                includeProperties: "Category")
            });
        }

        #endregion
    }
}

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoCapas.AccesoDatos.Data.Repository.IRepository;
using ProyectoCapas.Models;

namespace ProyectoCapas.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrador")]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ICategoryRepository.Add(category);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(category);
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return BadRequest();
            }
            else
            {
                Category category = new Category();
                category = _unitOfWork.ICategoryRepository.GetById(id);
                if (category == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(category);
                }
            }
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ICategoryRepository.Update(category);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(category);
        }
        #endregion

        #region Call Apis

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.ICategoryRepository.GetAll(x => x.IsActive) });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var category = _unitOfWork.ICategoryRepository.GetFirstOrDefault(x => x.Id == id && x.IsActive);
            if (category == null)
            {
                return Json(new { success = false, message = "La categoria no existe" });
            }
            _unitOfWork.ICategoryRepository.Delete(id);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Categoria eliminada exitosamente" });
        }

        #endregion
    }
}

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Areas/Admin/Controllers/SlidersController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoCapas.AccesoDatos.Data.Repository.IRepository;
using ProyectoCapas.Models;

namespace ProyectoCapas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public SlidersController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Slider slider)
        {
            string mainRoute = _webHostEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            if (files.Count() > 0)
            {
                string nameFile = Guid.NewGuid().ToString();
                string upload = Path.Combine(mainRoute, @"images\sliders");
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStreams = new FileStream(Path.Combine(upload, nameFile + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStreams);
                }

                slider.UrlImage = @"\images\sliders\" + nameFile + extension;

                _unitOfWork.ISliderRepository.Add(slider);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(slider);
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return BadRequest();
            }
            else
            {
                Slider slider = new Slider();
                slider = _unitOfWork.ISliderRepository.GetById(id);
                if (slider == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(slider);
                }
            }
        }

        [HttpPost]
        public IActionResult Edit(Slider slider)
        {
            string mainRoute = _webHostEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var sliderFromDb = _unitOfWork.ISliderRepository.GetById(slider.Id);

            if (files.Count() > 0)
            {
                string nameFile = Guid.NewGuid().ToString();
                string upload = Path.Combine(mainRoute, @"images\sliders");
                var extension = Path.GetExtension(files[0].FileName);

                //comprobar si la imagen existe
                var oldPath = Path.Combine(mainRoute, sliderFromDb.UrlImage.TrimStart('\\'));
                if (System.IO.File.Exists(oldPath))
                {
                    System.IO.File.Delete(oldPath);
                }

                //NUevamente subimos la imagen
                using (var fileStreams = new FileStream(Path.Combine(upload, nameFile + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStreams);
                }

                slider.UrlImage = @"\images\sliders\" + nameFile + extension;

                _unitOfWork.ISliderRepository.Update(slider);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                slider.UrlImage = sliderFromDb.UrlImage;
            }

            _unitOfWork.ISliderRepository.Update(slider);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Call Apis

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.ISliderRepository.GetAll(x => x.IsActive) });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var sliderFromDb = _unitOfWork.ISliderRepository.GetById(id);

            string mainRoute = _webHostEnvironment.WebRootPath;
            var pathOldImage = Path.Combine(mainRoute, sliderFromDb.UrlImage.TrimStart('\\'));

            //Comprobamos si la imagen existe
            if (System.IO.File.Exists(pathOldImage))
            {
                System.IO.File.Delete(pathOldImage);
            }


            if (sliderFromDb == null)
            {
                return Json(new { success = false, message = "El slider no existe" });
            }
            _unitOfWork.ISliderRepository.Delete(id);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Slider eliminado exitosamente" });
        }

        #endregion
    }
}

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoCapas.AccesoDatos.Data.Repository.IRepository;
using System.Security.Claims;

namespace ProyectoCapas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UsersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var userCurrent = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var list = _unitOfWork.IUserRepository.GetAll(x => x.Id != userCurrent.Value);

            return View(_unitOfWork.IUserRepository.GetAll(x => x.Id != userCurrent.Value));
        }

        [HttpGet]
        public IActionResult Block(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            _unitOfWork.IUserRepository.BlockUser(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult UnBlock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _unitOfWork.IUserRepository.UnBlockUser(id);

            return RedirectToAction("Index");
        }
    }
}

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoCapas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap5.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoCapas.styles.css" asp-append-version="true" />
    <!--Css -->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><img src="~/images/blog1.jpeg" width="80" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Home" asp-action="Index">
                                Inicio
                            </a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categorias</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Articles" asp-action="Index">Articulos</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Usuarios</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                    </ul>
                    <form class="search d-flex" asp-controller="Home" asp-action="ResultSearch" method="get">
                        <input class="form-control me-sm-2" type="search" name="searchString" placeholder="buscar">
                        <div class="input-group-append">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <!--Slider-->
        @if(ViewBag.IsHome == true)
        {
            <partial name="_Slider" />
        }
        
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Banner-->
    <div class="container-fluid banner-container">
        <div class="container banner-content">
            <button type="button" class="btn btn-success subscribe-btn">Suscribete a nuestro blog</button>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProyectoCapas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Views/Shared/_Slider.cshtml
@model ProyectoCapas.Models.ViewModel.HomeViewModel

<!--Slider-->

<div id="sliderImagenes" class="carousel slide">
    <div class="carousel-inner">
        @{
            var activeSliders = Model.listSliders.Where(x => x.State == true).ToList();
            int count = 0;
        }

        @foreach (var slider in activeSliders)
        {
            @* string dynamic = "";
            if(count == 0)
            {
                dynamic = "active";
            }
            else
            {
                dynamic = "inactive";
            } 
            count++*@
            var itemDynamico = count++ == 0 ? "active" : "inactive";

            <div class="carousel-item @itemDynamico">
                <img src="@Url.Content(slider.UrlImage)" class="d-block w-100" />
                <h1 class="text-center bg-light py-1" style="color:aliceblue;">@Html.Raw(slider)</h1>
            </div>
        }
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#sliderImagenes" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" data-bs-target="#sliderImagenes" data-bs-slide="prev">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
</div>

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Views/Shared/_ViewCreate.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
</div>

Semana15/Lunes_12_01/ProyectoCapas/ProyectoCapas/Views/Shared/_ViewEdit.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Editar</button>
    </div>
</div>