Semana20/Lunes_02_02/G7_Microservices/G7_Microservices.FrontEnd.Web/Controllers/AuthController.cs
using G7_Microservices.FrontEnd.Web.Models.Dto;
using G7_Microservices.FrontEnd.Web.Models.Dto.Auth;
using G7_Microservices.FrontEnd.Web.Services.IServices;
using G7_Microservices.FrontEnd.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace G7_Microservices.FrontEnd.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;

        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }

        #region Login
        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto loginRequestDto = new LoginRequestDto();
            return View(loginRequestDto);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
        {
            ResponseDto responseDto = new ResponseDto();
            responseDto = await _authService.LoginAsync(loginRequestDto);
            if (responseDto != null && responseDto.IsSucess)
            {
                LoginResponseDto loginResponseDto = new LoginResponseDto();
                loginResponseDto = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result));

                await SignInUser(loginResponseDto);
                _tokenProvider.SetToken(loginResponseDto.Token);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = responseDto.Message;
                return View(loginRequestDto);
            }


        }
        #endregion

        #region Register
        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Text = SD.RoleAdmin,
                    Value = SD.RoleAdmin,
                },
                new SelectListItem()
                {
                    Text = SD.RoleCustomer,
                    Value = SD.RoleCustomer,
                }
            };
            ViewBag.RoleList = roleList;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequestDto registerRequestDto)
        {
            ResponseDto responseDto = await _authService.RegisterAsync(registerRequestDto);
            ResponseDto assignRole;
            if (responseDto != null && responseDto.IsSucess)
            {
                if (string.IsNullOrEmpty(registerRequestDto.Role))
                {
                    registerRequestDto.Role = SD.RoleAdmin;
                }
                assignRole = await _authService.AssignRoleAsync(registerRequestDto);
                if (assignRole != null && assignRole.IsSucess)
                {
                    TempData["success"] = "Registro exitoso";

                    return RedirectToAction(nameof(Login));
                }
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }

            var roleList = new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Text = SD.RoleAdmin,
                    Value = SD.RoleAdmin,
                },
                new SelectListItem()
                {
                    Text = SD.RoleCustomer,
                    Value = SD.RoleCustomer,
                }
            };
            ViewBag.RoleList = roleList;
            return View(registerRequestDto);

        }
        #endregion

        #region logout
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }
        #endregion
        private async Task SignInUser(LoginResponseDto loginResponseDto)
        {
            var handlerToken = new JwtSecurityTokenHandler();
            var jwt = handlerToken.ReadJwtToken(loginResponseDto.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Name).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(x => x.Type == "role").Value));

            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

        }
    }
}

Semana20/Lunes_02_02/G7_Microservices/G7_Microservices.FrontEnd.Web/Controllers/CouponsController.cs
using G7_Microservices.FrontEnd.Web.Models.Dto;
using G7_Microservices.FrontEnd.Web.Models.Dto.Coupon;
using G7_Microservices.FrontEnd.Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace G7_Microservices.FrontEnd.Web.Controllers
{
    public class CouponsController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponsController(ICouponService couponService)
        {
            _couponService = couponService;
        }

        [HttpGet]
        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto> listCoupon = new List<CouponDto>();
            ResponseDto? responseDto = await _couponService.GetAllCouponsAsync();
            if (responseDto != null && responseDto.IsSucess)
            {
                listCoupon = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto?.Message;
            }
            return View(listCoupon);
        }

        #region Create
        [HttpGet]
        public async Task<IActionResult> CouponCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CouponCreate(CouponRequestDto couponRequestDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? responseDto = await _couponService.CreateCouponAsync(couponRequestDto);
                if (responseDto != null && responseDto.IsSucess)
                {
                    TempData["success"] = "Cupon creado con exito";
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message;
                    return View(couponRequestDto);
                }
            }
            return View(couponRequestDto);
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> CouponEdit(int couponId)
        {
            CouponDto? couponDto = new CouponDto();
            CouponRequestDto? couponRequestDto = new CouponRequestDto();
            ResponseDto? responseDto = await _couponService.GetCouponByIdAsync(couponId);
            if (responseDto != null && responseDto.IsSucess)
            {
                couponDto = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(responseDto?.Result));
                if (couponDto != null)
                {
                    couponRequestDto.Id = couponDto.Id;
                    couponRequestDto.Code = couponDto.Code;
                    couponRequestDto.DiscountAmount = couponDto.DiscountAmount;
                    couponRequestDto.MinimunAmount = couponDto.MinimunAmount;
                }
                return View(couponRequestDto);
            }
            else
            {
                TempData["error"] = responseDto?.Message;
                return View(couponRequestDto);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CouponEdit(CouponRequestDto couponRequestDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? responseDto = await _couponService.UpdateCouponAsync(couponRequestDto);
                if (responseDto != null && responseDto.IsSucess)
                {
                    TempData["success"] = "Cupon actualizado con exito";
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message;
                    return View(couponRequestDto);
                }
            }
            return View(couponRequestDto);
        }
        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> CouponDelete(int couponId)
        {
            CouponDto? couponDto = new CouponDto();

            ResponseDto? responseDto = await _couponService.GetCouponByIdAsync(couponId);
            if (responseDto != null && responseDto.IsSucess)
            {
                couponDto = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(responseDto?.Result));

                return View(couponDto);
            }
            else
            {
                TempData["error"] = responseDto?.Message;
                return View(couponDto);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CouponDelete(CouponDto couponDto)
        {
            ResponseDto? responseDto = await _couponService.DeleteCouponAsync(couponDto.Id);
            if (responseDto != null && responseDto.IsSucess)
            {
                TempData["success"] = "Cupon eliminado con exito";
                return RedirectToAction(nameof(CouponIndex));
            }
            else
            {
                TempData["error"] = responseDto?.Message;
                return View();
            }
        }
        #endregion
    }
}

Semana20/Lunes_02_02/G7_Microservices/G7_Microservices.FrontEnd.Web/Controllers/ProductsController.cs
using G7_Microservices.FrontEnd.Web.Models.Dto;
using G7_Microservices.FrontEnd.Web.Models.Dto.Product;
using G7_Microservices.FrontEnd.Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace G7_Microservices.FrontEnd.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> ProductIndex()
        {
            List<ProductDto>? listProducts = new();
            ResponseDto? responseDto = await _productService.GetAllProductsAsync();
            if (responseDto != null && responseDto.IsSucess)
            {
                listProducts = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto?.Message;
            }

            return View(listProducts);
        }

        #region Create
        [HttpGet]
        public async Task<IActionResult> ProductCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ProductCreate(ProductDto productDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? responseDto = await _productService.CreateProductsAsync(productDto);
                if (responseDto != null && responseDto.IsSucess)
                {
                    TempData["success"] = "Producto creado con exito";
                    return RedirectToAction(nameof(ProductIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message;
                    return View(productDto);
                }
            }
            return View(productDto);
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> ProductEdit(int productId)
        {
            ProductDto? productDto = new ProductDto();

            ResponseDto? responseDto = await _productService.GetProductByIdAsync(productId);
            if (responseDto != null && responseDto.IsSucess)
            {
                productDto = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(responseDto?.Result));

                return View(productDto);
            }
            else
            {
                TempData["error"] = responseDto?.Message;
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ProductEdit(ProductDto productDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? responseDto = await _productService.UpdateProductsAsync(productDto);
                if (responseDto != null && responseDto.IsSucess)
                {
                    TempData["success"] = "Producto actualizado con exito";
                    return RedirectToAction(nameof(ProductIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message;
                    return View(productDto);
                }
            }
            return View(productDto);
        }
        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> ProductDelete(int productId)
        {
            ProductDto? productDto = new ProductDto();

            ResponseDto? responseDto = await _productService.GetProductByIdAsync(productId);
            if (responseDto != null && responseDto.IsSucess)
            {
                productDto = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(responseDto?.Result));

                return View(productDto);
            }
            else
            {
                TempData["error"] = responseDto?.Message;
                return View(productDto);
            }
        }

        [HttpPost]
        public async Task<IActionResult> ProductDelete(ProductDto productDto)
        {
            ResponseDto? responseDto = await _productService.DeleteProductsAsync(productDto.Id);
            if (responseDto != null && responseDto.IsSucess)
            {
                TempData["success"] = "Producto eliminado con exito";
                return RedirectToAction(nameof(ProductIndex));
            }
            else
            {
                TempData["error"] = responseDto?.Message;
                return View();
            }
        }
        #endregion
    }
}

Semana20/Lunes_02_02/G7_Microservices/G7_Microservices.FrontEnd.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - G7_Microservices.FrontEnd.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min5.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/G7_Microservices.FrontEnd.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">G7_Microservices.FrontEnd.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Administracion de Contenido
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupons" asp-action="CouponIndex">Cupones</a></li>
                                <li><a class="dropdown-item" asp-controller="Products" asp-action="ProductIndex">Productos</a></li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="ShoppingCart" asp-action="ShoppingCartIndex">
                                        &nbsp; <i class="bi bi-cart"></i>&nbsp;
                                    </a>
                                </li>
                                <li><hr class="dropdown-divider" /></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Bienvenido, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - G7_Microservices.FrontEnd.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>